name: Publish Mod

on:
  workflow_dispatch:
    inputs:
      release_modrinth:
        type: boolean
        description: 'Modrinth Release'
        default: false
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/openjdk/jdk:25-ubuntu
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: publish the thing
        run: ./gradlew build publishMods
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          RELEASE_MODRINTH: ${{ inputs.release_modrinth }}
